# Generated by Django 3.2.9 on 2021-12-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_ta_transactions_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta_transactions',
            name='employee_id',
            field=models.IntegerField(),
        ),
    ]
