# Generated by Django 3.2.9 on 2021-12-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_rename_ta_transactions_ta_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ta_transaction',
            name='matches',
        ),
    ]
