# Generated by Django 3.2.9 on 2022-01-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_rename_matches_ta_transaction_processed_late_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta_transaction_processed',
            name='late_leaving',
            field=models.BooleanField(default=False),
        ),
    ]
