# Generated by Django 3.2.9 on 2022-01-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_ta_transaction_processed_late_leaving'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta_transaction_processed',
            name='transaction_date',
            field=models.DateField(auto_now=True),
        ),
    ]
