# Generated by Django 3.2.9 on 2022-01-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_ta_transaction_processed_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_proccessed_transactions', models.IntegerField()),
            ],
        ),
    ]
