# Generated by Django 3.2.9 on 2022-01-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_statistic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistic',
            new_name='Statistics',
        ),
    ]
