# Generated by Django 3.2.9 on 2022-01-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_rename_statistic_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='late_gap',
            field=models.IntegerField(default=15),
        ),
    ]
