# Generated by Django 3.2.9 on 2022-01-09 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_statistics_late_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta_transaction_processed',
            name='working_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
