# Generated by Django 3.2.9 on 2022-01-09 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_ta_transaction_processed_working_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta_transaction_processed',
            name='working_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
