# Generated by Django 3.2.9 on 2021-11-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start_time', models.DateField()),
                ('shift_end_time', models.DateField()),
                ('shift_id', models.IntegerField(max_length=200)),
            ],
        ),
    ]
