# Generated by Django 3.2.9 on 2021-11-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='shift_id',
            field=models.IntegerField(),
        ),
    ]
