# Generated by Django 3.2.9 on 2021-11-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_alter_shifts_shift_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='shift_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='shift_start_time',
            field=models.DateTimeField(),
        ),
    ]
