# Generated by Django 3.2.9 on 2021-11-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_alter_shifts_shift_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='shift_id',
        ),
    ]
