# Generated by Django 3.2.9 on 2021-11-10 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_start_date', models.DateField()),
                ('schedule_end_date', models.DateField()),
                ('schedule_id', models.IntegerField(max_length=200)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shifts')),
            ],
        ),
    ]
