# Generated by Django 3.2.9 on 2021-11-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_schedules_schedule_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='schedule_id',
        ),
    ]
